### ISSUE TITLE
It says you are high iq’s it seems off you don’t have high iq’s 

### ISSUE THREAD

**Issue by espero-dev** [Windows81/roblox-celebrity-tracker#2]
You lied when I watch you and listen to you through your devices it’s not high iq it’s low iq

**Comment by Windows81** [comment]
It sèéms off that my IQ is not 666 indeed.  It's also less than 250 too!

**Comment by espero-dev** [comment]
Hmm let me guess 50

**Comment by Windows81** [comment]
Sorry for the late response.  My IQ is indeed 50.  I'm closing the issue because you have resolved it for me.
